[package]
name = "UniTyLab-Thesis-Template"
version = "0.0.1"
entrypoint = "Template/config.typ"

authors = ["@Ferrys93de"]
license = "https://opensource.org/license/mit"
description = "The official Thesis Template from the Usability and Interaction Technology Laboratory (UniTyLab) of the Heilbronn University (HHN)"

homepage = "https://www.hs-heilbronn.de/en"
repository = ""
keywords = ["hhn", "hochschule heilbronn", "heilbronn university", "unitylab", "thesis", "documentation"]
categories = ["thesis", "report"]
exclude = [""]

[template]
path = "Studi"
entrypoint = "Document.typ"
thumbnail = "Template/00-Title/HHN_Logo_EN_slim.png"